version: '3'

services:
  sistemati-api:
    container_name: app-sistemati-api
    hostname: sistemati-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:8080"        
    command: bash -c "npm run start"


