up:
	docker-compose --compatibility up -d

down: 
	docker-compose down

get-in:
	docker exec -it app-sistemati-api bash

restart:
	docker-compose down --rm all ; docker-compose --compatibility up --force-recreate
