up:
	docker-compose --compatibility up -d

down: 
	docker-compose down

get-in:
	docker exec -it app-153-api bash

logs:
	docker-compose logs -f

restart:
	docker-compose down ; docker-compose --compatibility up -d
